//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a Ã©tÃ© gÃ©nÃ©rÃ© par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportÃ©es Ã  ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est rÃ©gÃ©nÃ©rÃ©.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
    public class Character : Being
    {
        public Transform FogOfWarPlane;
        protected int idGroupe;
        protected override void Start()
        {
            base.Start();
            idGroupe = 0;
        }

        protected override void Update()
        {
            base.Update();

            //Fog of war update; set position and perception of the object and the plane
            Vector3 screenPos = Camera.main.WorldToScreenPoint(transform.position);
            Ray rayToPlayerPos = Camera.main.ScreenPointToRay(screenPos);
            RaycastHit hit;
            if (Physics.Raycast(rayToPlayerPos, out hit, 1000))
            {
                FogOfWarPlane.GetComponent<Renderer>().material.SetFloat("_player_per" + idGroupe, 7.5f);
                FogOfWarPlane.GetComponent<Renderer>().material.SetVector("_Player_Pos_" + idGroupe.ToString(), hit.point);
            }
        }
        protected override void GetSensorPositionData(out Vector3 a_position)
        {
            base.GetSensorPositionData(out a_position);
        }
    }
}

