//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
	public class Character:Being
	{
		protected Item[] Inventaire;
		protected override void Start ()
		{
			base.Start ();
			StartCoroutine(base.Iainit ());
		}
	
		protected override void Update ()
		{
			base.Update ();
			if (base.target != null) {
				base.move(target.gameObject.transform.position);
			}
		}
		protected override void GetSensorPositionData (out Vector3 a_position)
		{
			base.GetSensorPositionData (out a_position);
		}
	}
}

