//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a Ã©tÃ© gÃ©nÃ©rÃ© par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportÃ©es Ã  ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est rÃ©gÃ©nÃ©rÃ©.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
    public class Character : Being
    {
        public Transform FogOfWarPlane;
        protected int idGroupe;
        protected override void Start()
        {
            base.Start();
            idGroupe = 0;
        }

        protected override void Update()
        {
            base.Update();

           
        }
        protected override void GetSensorPositionData(out Vector3 a_position)
        {
            base.GetSensorPositionData(out a_position);
        }
    }
}

