//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Synapse.Runtime;
namespace AssemblyCSharp
{
    public class Enemy : Being
    {
        private Brain synapseBrain;
		private Brain synapseBrain2;
        int motivation = 50;
		int MotivationR=75;
        protected override void Start()
        {
            base.Start();
            StartCoroutine("StartAI");
        }
        IEnumerator StartAI()
        {
            synapseBrain = new SynapseLibrary_IA.Ennemy.Perception(this);
			synapseBrain2 = new SynapseLibrary_IA.Ennemy.Collector (this);
            while (Application.isPlaying && synapseBrain != null&&synapseBrain2!=null)
            {
                AIUpdate();
                yield return new WaitForSeconds(1);
            }
        }
        private void AIUpdate()
        {
			if (synapseBrain.Process() == false)
			{
				if (synapseBrain2.Process () == false) {
				}
			}

           

        }
        protected override void Update()
        {
            base.Update();
        }
        protected override void GetSensorPositionData(out Vector3 a_position)
        {
            base.GetSensorPositionData(out a_position);
        }
        protected void GetSensorPerceptionData(out int percept)
        {
            percept = base.perception;
        }
		protected void GetSensorMotivationRData(out int motiv)
		{
			motiv = MotivationR;
		}
        protected void GetSensorMotivationData(out int motiv)
        {
            motiv = motivation;
        }
        void OnDestroy()
        {
        }
		protected object[] GetLayerResourcesData()
		{
			return GameController.ressources.ToArray();
		}
        protected object[] GetLayerOpponentData()
        {
            return GameController.Units[0].ToArray();
        }
		protected void DesireCollectCallback(object ressource){
			Debug.Log ("collect");
			ResourcesManager res = ressource as ResourcesManager;
			if (!isCollecting) {
				launchCollect (res.gameObject);
			}
		}
        protected void DesireInsightCallback(object opponent)
        {
			Debug.Log ("attack");
            Being target = opponent as Being;
            float dist = Vector3.Distance(this.transform.position, target.transform.position);
            if (dist < target.scope)
            {
                base.launchAttack(target.gameObject);
            }
            else {
                base.move(target.transform.position);
            }
        }
    }
}

