//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Enemy:Being
	{
		public static List<Enemy> Instance= new List<Enemy>();
		protected override void Start ()
		{
			base.Start ();
			Instance.Add (this);
		}
		protected override void Update ()
		{
			base.Update ();
		}
		protected override void GetSensorPositionData (out Vector3 a_position)
		{
			base.GetSensorPositionData (out a_position);
		}
	 	void OnDestroy(){
			Instance.Remove (this);
		}
	}
}

