//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public class equipment : Item
    {
        //0 arme; 1 armure
        public int typeEquip;
        public int damage;
        public int bonus;
        public int bonusScope;
        public equipment(string _name, string path, int type) : base(_name, path, type)
        {

        }
        public equipment(string _name, string _path, int _type, int _damage, int _bonus, int _bonusScope, int _typeEquip) : base(_name, _path, _type)
        {
            damage = _damage;
            bonus = _bonus;
            bonusScope = _bonusScope;
            typeEquip = _typeEquip;
        }
    }
}

